inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Rakefile
    - config/**/*
    - test/**/*

Style/FrozenStringLiteralComment:
  Enabled: false  # 早いうちに 3.0 に上げるので無視する

